FROM maven:3.9-eclipse-temurin-25 AS BUILD
COPY . /src
WORKDIR /src
RUN mvn package -Dmaven.test.skip=true

FROM ubuntu/jre:25-26.04_stable
EXPOSE 8080
WORKDIR /app
ARG JAR=library-0.0.1-SNAPSHOT.jar

COPY --from=BUILD /src/target/$JAR /app.jar
ENTRYPOINT ["/usr/bin/java","-jar","/app.jar"]
