CREATE TABLE patron_database_entity (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patron_type VARCHAR(100) NOT NULL,
    patron_id UUID UNIQUE,
    email_address VARCHAR(254) NOT NULL UNIQUE
);

CREATE TABLE hold_database_entity (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id UUID NOT NULL,
    patron_id UUID NOT NULL,
    library_branch_id UUID NOT NULL,
    patron_database_entity INTEGER NOT NULL,
    till TIMESTAMP NOT NULL
);

CREATE TABLE overdue_checkout_database_entity (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id UUID NOT NULL,
    patron_id UUID NOT NULL,
    library_branch_id UUID NOT NULL,
    patron_database_entity INTEGER NOT NULL
);

CREATE TABLE book_database_entity (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  book_id UUID UNIQUE,
  book_type VARCHAR(100) NOT NULL,
  book_state VARCHAR(100) NOT NULL,
  available_at_branch UUID,
  on_hold_at_branch UUID,
  on_hold_by_patron UUID,
  checked_out_at_branch UUID,
  checked_out_by_patron UUID,
  on_hold_till TIMESTAMP,
  version INTEGER);

CREATE SEQUENCE book_database_entity_seq;

CREATE TABLE checkouts_sheet (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  book_id UUID NOT NULL,
  status VARCHAR(20) NOT NULL,
  checkout_event_id UUID UNIQUE,
  checked_out_by_patron_id UUID,
  checked_out_at TIMESTAMP,
  returned_at TIMESTAMP,
  checked_out_at_branch UUID,
  checkout_till TIMESTAMP);

CREATE TABLE holds_sheet (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  book_id UUID NOT NULL,
  status VARCHAR(20) NOT NULL,
  hold_event_id UUID UNIQUE,
  hold_at_branch UUID,
  hold_by_patron_id UUID,
  hold_at TIMESTAMP,
  hold_till TIMESTAMP,
  expired_at TIMESTAMP,
  canceled_at TIMESTAMP,
  checked_out_at TIMESTAMP);

CREATE SEQUENCE holds_sheet_seq;
CREATE SEQUENCE checkouts_sheet_seq;
